### ISSUE TITLE
java.lang.NoClassDefFoundError: com/gmail/goosius/siegewar/TownOccupationController

### ISSUE THREAD

**Issue by Akiranya** [TownyAdvanced/TownyResources#35]
Hi, I've just updated TR from 0.11 to 0.15 and this error seems to come out at certain interval /w\

```
[19:57:33 ERROR]: Could not pass event NewShortTimeEvent to TownyResources v0.0.15
java.lang.NoClassDefFoundError: com/gmail/goosius/siegewar/TownOccupationController
        at io.github.townyadvanced.townyresources.controllers.TownResourceProductionController.recalculateProductionForOneNation(TownResourceProductionController.java:157) ~[TownyResources-0.0.15.jar:?]
        at io.github.townyadvanced.townyresources.controllers.TownResourceProductionController.recalculateProductionForAllNations(TownResourceProductionController.java:103) ~[TownyResources-0.0.15.jar:?]
        at io.github.townyadvanced.townyresources.controllers.TownResourceProductionController.recalculateAllProduction(TownResourceProductionController.java:29) ~[TownyResources-0.0.15.jar:?]
        at io.github.townyadvanced.townyresources.listeners.TownyResourcesTownyEventListener.onNewShortTime(TownyResourcesTownyEventListener.java:64) ~[TownyResources-0.0.15.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor910.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Paper-257]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.17.1.jar:git-Paper-257]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-257]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) [patched_1.17.1.jar:git-Paper-257]
        at com.palmergames.bukkit.towny.tasks.ShortTimerTask.run(ShortTimerTask.java:28) [Towny-0.97.1.7.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) [patched_1.17.1.jar:git-Paper-257]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) [patched_1.17.1.jar:git-Paper-257]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.17.1.jar:git-Paper-257]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

config.yml

```
version:
  # This is the current version.  Please do not edit.
  version: 0.0.15
# The language file you wish to use
language: chinese.yml
 
# If true, the TownyResources system is enabled.
# if false, the TownyResources system is disabled.
enabled: 'true'
 
 
############################################################
# +------------------------------------------------------+ #
# |             Resource Extraction Limits               | #
# +------------------------------------------------------+ #
############################################################
 
resource_extraction_limits:
 
  # If true, then daily player resource extraction limits are enabled.
  # If false, then daily player resource extraction limits are disabled.
  enabled: 'false'
 
  # The cooldown after a player receives a daily-limit warning message.
  # During this time they cannot receive another daily-limit warning message for the same material.
  cooldown_after_daily_limit_warning_message_millis: '5000'
 
  # This list shows the resource extraction categories.
  # 
  # Each category is enclosed in curly brackets, and has 3 parts:
  # 1 - The name of the category (used for messaging)
  # 2-  The daily limit per player (in stacks)
  # 3-  The list of materials in the category
  categories: ''
 
 
############################################################
# +------------------------------------------------------+ #
# |                  Town Resources                      | #
# +------------------------------------------------------+ #
############################################################
 
town_resources:
 
 
  surveys:
 
    # If true, players can do surveys.
    # if false, they cannot.
    enabled: 'true'
 
    # This list of values determines how much it costs to do a survey for each resource level.
    # Example: If the first value is 250, then it will cost 250 to survey and discover the level 1 resource.
    cost_per_resource_level: 250, 1000, 4000, 16000
 
    # This list of values determines how much many townblocks a town must have to DISCOVER each level of resource.
    # Example: If the first value is 10, then the town must have 10 townblocks to survey and discover the level 1 resource.
    num_townblocks_requirement_per_resource_level: 10, 50, 100, 200
 
 
  production:
 
    # If true, towns produce resources.
    # if false, towns do not produce resource.
    enabled: 'true'
 
    # This list of values determines the level a town needs to be, to PRODUCE its resources.
    # Example: If the first value is 1, then the town has to be level 1 to produce its level 1 resource.
    town_level_requirement_per_resource_level: 2, 4, 6, 8
 
    # This list of values determines the productivity of each level of resource.
    # Example: If the second value is 200, then the level 2 resource of a town will be 200% productive.
    productivity_percentage_per_resource_level: 100, 200, 300, 400
 
    # This value determines the limit of how many resources of each type can be stored for collection.
    # Example: If this value 3, and the daily production amount is 32 ..... then the storage limit is 96.
    storage_limit_modifier: '6'
 
    # The nation of a town gets this percentage of town production, as long as the town is not occupied.
    # The town gets the rest.
    nation_tax_percentage: '25'
 
    # If a town is occupied, the occupying nation gets this percentage of town production.
    # The town gets the rest.
    occupying_nation_tax_percentage: '50'
 
 
  offers:
 
    # This list shows the survey offer categories.
    # 
    # Each category is enclosed in curly brackets, and has 4 parts:
    # 1 - The name of the category (used for messaging)
    # 2 - The discovery weight of the category (used during discovery)
    # 3-  The base amount of the offer (in stacks)
    # 4-  The list of materials in the category
    # 
    # The default values give a weight of 200 to strategic resources (coal, iron etc.), and 100 to most non-strategic resources. (wheat, quartz etc.)
    # This gives each survey approx. 30% chance to discover a strategic resources, and a 70% to discover a non-strategic resource.
    categories: |
      {common_dirt, 25, 1, DIRT},
      {gravel, 100, 0.5, GRAVEL},
      {sand, 100, 1, SAND},
      {common_rocks, 100, 1, STONE, COBBLESTONE},
      {uncommon_rocks, 100, 0.5, DIORITE, ANDESITE, GRANITE},
      {terracotta, 100, 0.25, TERRACOTTA},
      {quartz, 100, 0.5, QUARTZ_BLOCK},
      {prismarine, 100, 0.125, PRISMARINE},
      {obsidian, 100, 0.0625, OBSIDIAN},
      {clay, 100, 0.5, CLAY_BALL},
      {ice, 25, 0.5, ICE},
      {snow, 25, 0.5, SNOWBALL},
      {coal, 200, 0.5, COAL},
      {iron, 200, 0.25, RAW_IRON},
      {gold, 200, 0.125, RAW_GOLD},
      {copper, 100, 0.125, RAW_COPPER},
      {emeralds, 200, 0.125, EMERALD},
      {diamonds, 200, 0.0625, DIAMOND},
      {redstone, 100, 0.5, REDSTONE},
      {ancient_debris, 200, 0.03125, ANCIENT_DEBRIS},
      {wood, 200, 1, OAK_LOG, SPRUCE_LOG, BIRCH_LOG, JUNGLE_LOG, ACACIA_LOG, DARK_OAK_LOG, OAK_WOOD, SPRUCE_WOOD, BIRCH_WOOD, JUNGLE_WOOD, ACACIA_WOOD, DARK_OAK_WOOD},
      {wheat, 100, 0.5, WHEAT},
      {carrots, 100, 0.5, CARROT},
      {potatoes, 100, 0.5, POTATO},
      {beetroots, 100, 0.5, BEETROOT},
      {pumpkin_seeds, 100, 0.5, PUMPKIN_SEEDS},
      {melon_slices, 100, 0.5, MELON_SLICE},
      {cocoa_plants, 100, 0.5, COCOA_BEANS},
      {pumpkin_blocks, 100, 0.5, PUMPKIN},
      {kelp, 100, 0.5, KELP},
      {bamboo, 100, 0.5, BAMBOO},
      {cactus, 100, 0.5, CACTUS},
      {mushrooms, 100, 0.5, BROWN_MUSHROOM, RED_MUSHROOM},
      {apple_trees, 100, 0.0625, APPLE},
      {vines, 100, 0.125, VINE},
      {fish, 100, 0.5, COD, SALMON, PUFFERFISH, TROPICAL_FISH},
      {wool, 100, 1, WHITE_WOOL},
      {gunpowder, 200, 0.125, GUNPOWDER},
      {string, 100, 0.125, STRING},
      {spider_eyes, 100, 0.125, SPIDER_EYE},
      {feathers, 100, 0.125, FEATHER},
      {leather, 100, 0.125, LEATHER},
      {rabbit_hides, 100, 0.125, RABBIT_HIDE},
      {rotten_flesh, 100, 0.5, ROTTEN_FLESH},
      {bones, 100, 0.25, BONE},
      {pork, 100, 0.125, PORKCHOP},
      {mutton, 100, 0.125, MUTTON},
      {beef, 100, 0.125, BEEF},
      {chickens, 100, 0.125, CHICKEN},
      {eggs, 100, 0.125, EGG},
      {ender_pearls, 100, 0.125, ENDER_PEARL}
      {slime, 100, 0.25, SLIME_BALL}
 
 
  language:
 
    # If you have the LanguageUtils plugin installed, materials will be automatically translated into this locale/language.
    materials_display_language: zh_cn
```

**Comment by Goosius1** [comment]
Ok thanks, I will have a look at this

**Comment by Akiranya** [comment]
The error would came out once at server startup. Now it looks all good.

Thanks!
