### ISSUE TITLE
[Server thread/ERROR]: Could not pass event PlayerFishEvent to TownyResources v0.1.1

### ISSUE THREAD

**Issue by noisereactz1** [TownyAdvanced/TownyResources#53]
Hey guys,

after a few hours of fishing i reached the extraction limit of the fishes. From there no message is showing up just the fishing rod is stucking in the water when i want to pull it out of the water with the next fish.

My Towny Version is the newest and also townyresources is uptodate. 
My Server Version is : Paper 1.16.5

Please help me and fix this <3

This are my category configs:
categories: '{fish, 5.0, COD, SALMON, PUFFERFISH, TROPICAL_FISH},{food, 0.5, PORKCHOP, CHICKEN, BEEF, RABBIT, MUTTON, COOKED_PORKCHOP, COOKED_CHICKEN, COOKED_BEEF, COOKED_RABBIT, COOKED_MUTTON},{food, 10.0, CARROT, POTATO},{food, 0.5, SWEET_BERRIES, BEETROOT},{material, 10.0, WHEAT},{material, 0.5, BROWN_MUSHROOM, RED_MUSHROOM},{material, 0.5, KELP},{material, 0.5, MILK_BUCKET},{food, 0.5, MELON_SLICE}'
 

ERROR-LOG

[17:59:33] [Server thread/ERROR]: Could not pass event PlayerFishEvent to TownyResources v0.1.1
java.util.IllegalFormatConversionException: d != java.lang.String
	at java.util.Formatter$FormatSpecifier.failConversion(Unknown Source) ~[?:1.8.0_301]
	at java.util.Formatter$FormatSpecifier.printInteger(Unknown Source) ~[?:1.8.0_301]
	at java.util.Formatter$FormatSpecifier.print(Unknown Source) ~[?:1.8.0_301]
	at java.util.Formatter.format(Unknown Source) ~[?:1.8.0_301]
	at java.util.Formatter.format(Unknown Source) ~[?:1.8.0_301]
	at java.lang.String.format(Unknown Source) ~[?:1.8.0_301]
	at io.github.townyadvanced.townyresources.settings.TownyResourcesTranslation.of(TownyResourcesTranslation.java:89) ~[?:?]
	at io.github.townyadvanced.townyresources.controllers.PlayerExtractionLimitsController.sendLimitReachedWarningMessage(PlayerExtractionLimitsController.java:375) ~[?:?]
	at io.github.townyadvanced.townyresources.controllers.PlayerExtractionLimitsController.processPlayerFishEvent(PlayerExtractionLimitsController.java:323) ~[?:?]
	at io.github.townyadvanced.townyresources.listeners.TownyResourcesBukkitEventListener.onPlayerFishEvent(TownyResourcesBukkitEventListener.java:92) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor576.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-788]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-788]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-788]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-788]
	at net.minecraft.server.v1_16_R3.EntityFishingHook.b(EntityFishingHook.java:497) ~[patched_1.16.5.jar:git-Paper-788]
	at net.minecraft.server.v1_16_R3.ItemFishingRod.a(ItemFishingRod.java:28) ~[patched_1.16.5.jar:git-Paper-788]
	at net.minecraft.server.v1_16_R3.ItemStack.a(ItemStack.java:434) ~[patched_1.16.5.jar:git-Paper-788]
	at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:449) ~[patched_1.16.5.jar:git-Paper-788]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1787) ~[patched_1.16.5.jar:git-Paper-788]
	at net.minecraft.server.v1_16_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:32) ~[patched_1.16.5.jar:git-Paper-788]
	at net.minecraft.server.v1_16_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:9) ~[patched_1.16.5.jar:git-Paper-788]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-788]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-788]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-788]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-788]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-788]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1266) ~[patched_1.16.5.jar:git-Paper-788]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1259) ~[patched_1.16.5.jar:git-Paper-788]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-788]
	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1220) ~[patched_1.16.5.jar:git-Paper-788]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1134) ~[patched_1.16.5.jar:git-Paper-788]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-788]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_301]

**Comment by LlmDl** [comment]
Do you use a custom language file?

**Comment by noisereactz1** [comment]
i only changed the text in the language file between the ' ', no parameters or something else :/

**Comment by LlmDl** [comment]
It would be helpful to see your language file.

**Comment by noisereactz1** [comment]
for sure, do you need anything else? :)

--

name: TownyResources
version: 0.06
language: english
author: Goosius
website: 'https://github.com/TownyAdvanced/TownyResources'
description: >
    Language file for all game messages.  Do not alter this file.
    If you wish to change any of the entries, make a copy named something else.
    Alternate language files can be enabled by altering the
    [language] entry in config.yml
#
#
#         You MUST retain spacing in the texts.
#  If a text begins or ends with a space, it must remain that way.
#
#
#       %s = data to be supplied by the plugin.

# Text colouring
# --------------
# Black = &0, Navy = &1, Green = &2, Blue = &3, Red = &4
# Purple = &5, Gold = &6, LightGray = &7, Gray = &8
# DarkPurple = &9, LightGreen = &a, LightBlue = &b
# Rose = &c, LightPurple = &d, Yellow = &e, White = &f

plugin_prefix: ''
msg_err_command_disable: '&cYou don''t have enough permissions for that command.'

### Reloading
townyresources_reloaded_successfully: "TownyResources reloaded successfully."
townyresources_failed_to_reload: "TownyResources failed to reload."
admin_help_reload: 'Reload TownyResources.'

### Town Screen
town.screen.header: "&2Fabrikproduktion:"
town.screen.daily.production: '&2 > Produktion pro Tag &a[%s]&2: &f'
town.screen.available.for.collection: '&2 > Zur Abholung bereit &a[%s]&2: &f'

### Nation Screen
nation.screen.header: "&2Fabrikproduktion:"
nation.screen.daily.production: '&2 > Produktion pro Tag &a[%s]&2: &f'
nation.screen.available.for.collection: '&2 > Zur Abholung bereit &a[%s]&2: &f'

### Surveys 
help_survey: 'Survey the town at your current location, to discover new resources.'
discovery.success: "&b%s has discovered %s at %s!. Tägliche Produktion: %d %s."

msg_err_survey_no_town: "&cThere is no town here to survey."
msg_err_survey_all_resources_already_discovered: "&cAlle verfügbaren Resourcen der Stadt wurden bereits freigeschaltet."
msg_err_survey_not_enough_townblocks: "&cDie Stadt besitzt nicht genug Fläche(Chunks) um die nächste Resource zu produzieren. Benötigt: %d, Aktuell: %d"
msg_err_survey_too_expensive: "&cDu hast nicht Genug Bargeld um die nächste Produktionsstufe freizuschalten. Benötigt: %s, Vermögen: %s"
msg_err_not_enough_offers_left: "&cSurvey not possible, because there are no offers left on the configured offers list."

### Production
production.message: "&b%s Fabriken in verschiedenen Städen haben Resourcen produziert."

### Collection
help_towncollect: 'Hole die Items aus den Fabriken deiner Stadt.'
help_nationcollect: 'Hole die Items aus den Fabriken deiner Nation.'

resource.towncollect.success: "&2Du hast alle Resourcen deiner Stadt abgeholt."
resource.nationcollect.success: "&2Du hast alle Resourcen deiner Nation abgeholt."

msg_err_cannot_towncollect_not_a_town_member: "&cYou must be a member of a town to collect town resources."
msg_err_cannot_towncollect_not_in_own_town: "&cMach dich auf in deine Stadt um die Resourcen abzuholen"
msg_err_cannot_towncollect_no_resources_available: '&cThere are no town resources available for collection.'

msg_err_cannot_nationcollect_not_a_town_member: "&cYou must be a member of a town to collect nation resources."
msg_err_cannot_nationcollect_not_a_nation_member: "&cYou must be a member of a nation to collect nation resources."
msg_err_cannot_nationcollect_not_in_capital: "&cYou must be in the capital to collect nation resources."
msg_err_cannot_nationcollect_no_resources_available: '&cThere are no nation resources available for collection.'

msg_err_cannot_collect_uknown_material: "&cUnknown Material: %s. Cannot collect this resource."

# Player Extraction Limits
msg_error_daily_extraction_limit_reached: "Du kannst nur &2%d &c%s &fpro Tag einsammeln. Suche nach der nächsten Nahrungsquelle."
daily_extraction_limits_reset: "&bAll daily extraction limits have been reset."

# Resource Categories
# The format of each of these is:  'extraction name, discovery name'
resource_category_common_dirt: 'common dirt, common dirt'
resource_category_uncommon_dirt: 'uncommon dirt, uncommon dirt'
resource_category_rare_dirt: 'rare dirt, rare dirt'
resource_category_gravel: 'Gravel, Gravel'
resource_category_sand: 'Sand, Sand'
resource_category_wood: 'Wood, "wood'
resource_category_common_rocks: 'common rocks, common rocks'
resource_category_uncommon_rocks: 'uncommon rocks, uncommon rocks'
resource_category_terracotta: 'Terracotta, terracotta'
resource_category_quartz: 'Quartz, Quartz'
resource_category_prismarine: 'Prismarine, Prismarine'
resource_category_obsidian: 'Obsidian, Obsidian'
resource_category_clay: 'Clay, Clay'
resource_category_ice: 'Ice, Ice' 
resource_category_snow: 'Snow, Snow'
resource_category_coal: 'Coal, Kohle'
resource_category_iron: 'Iron, Eisen'
resource_category_gold: 'Gold, Gold'
resource_category_gold_nugget: 'Gold Nugget, Gold'
resource_category_copper: 'Copper, Copper'
resource_category_emeralds: 'Emeralds, Emeralds'
resource_category_lapis_lazuli: 'Lapis Lazuli, Lapis Lazuli'
resource_category_diamonds: 'Diamonds, Diamenten'
resource_category_netherrack: 'Netherrack, Netherrack'
resource_category_nether_quartz: 'Nether Quartz, Nether Quartz'
resource_category_glowstone: 'Glowstone, Glowstone'
resource_category_end_stone: 'End Stone, End Stone'
resource_category_ancient_debris: 'Ancient Debris, Antiker Schrott'
resource_category_wool: 'Wool, a flock of sheep'
resource_category_coral: 'Coral, Coral'
resource_category_wheat: 'Wheat, fertile soil'
resource_category_carrots: 'Carrots, fertile soil'
resource_category_potatoes: 'Potatoes, fertile soil'
resource_category_beetroot: 'Beetroot, fertile soil'
resource_category_pumpkin_seeds: 'Pumpkin Seeds, fertile soil'
resource_category_melon_slice: 'Melon Slice, fertile soil'
resource_category_cocoa_beans: 'Cocoa Beans, fertile soil'
resource_category_pumpkin_blocks: 'Pumpkin Blocks, fertile soil'
resource_category_melon_blocks: 'Melon Blocks, fertile soil'
resource_category_cocoa_pods: 'Cocoa Pods, fertile soil'
resource_category_kelp: 'Kelp, Kelp'
resource_category_bamboo: 'Bamboo, fertile soil'
resource_category_cactus: 'Cactus, fertile soil'
resource_category_mushrooms: 'Mushrooms, Mushrooms'
resource_category_apples: 'Apples, an orchard'
resource_category_vines: 'Vines, Vines'
resource_category_nether_wart: 'Nether Wart, Nether Wart'
resource_category_chorus_fruit: 'Chorus Fruit, Chorus Fruit'
resource_category_fish: 'Fish, a shoal of fish'
resource_category_gunpowder: 'Gunpowder, Gunpowder'
resource_category_string: 'String, a nest of spiders'
resource_category_spider_eyes: 'Spider Eyes, a nest of spiders'
resource_category_feathers: 'Feathers, a flock of chickens'
resource_category_leather: 'Leather, a herd of cows'
resource_category_rabbit_hides: 'Rabbit Hides, a herd of rabbits'
resource_category_rotten_flesh: 'Rotten Flesh, a nest of zombies'
resource_category_bones: 'Bones, a nest of skeletons'
resource_category_pork: 'Pork, a herd of pigs'
resource_category_mutton: 'Mutton, a herd of sheep'
resource_category_beef: 'Beef, a herd of cows'
resource_category_chickens: 'Chicken, a flock of chickens'
resource_category_eggs: 'Eggs, a flock of hens'
resource_category_ender_pearls: 'Ender Pearls, a nest of endermen'

#Added in 0.03
resource_category_slime: 'Slime, a nest of slimes'

#Added in 0.04
msg_confirm_survey: "You are about to survey the town of %s for its level %d resource. This will cost %s. Do you wish to proceed ?"
msg_err_level_x_resource_already_discovered: "The level %d resource has already been discovered."
msg_err_cannot_collect_unknown_material: "Cannot collect the following unknown material: %s"

#Added in 0.05
msg_confirm_survey_town_level_warning: "&cWARNING: Although the resource can be discovered, the town does not have a large enough population to produce it. Required Town Level: %d, Actual Town Level %d."

#Added in 0.06
admin_help_reroll: "Reroll all currently discovered resources."
msg_confirm_reroll: "&cWARNING: You are about to re-roll all discovered town resources. This will affect all towns which have already discovered resources."
all_resources_rerolled: "All discovered town resources have been rerolled"

**Comment by LlmDl** [comment]
for the msg_error_daily_extraction_limit_reached message you switched the %s and %d around.

msg_error_daily_extraction_limit_reached: "&cDaily extraction limit reached for %s (%d)" is how it looks by default.
